# Generated by Django 3.1.1 on 2020-11-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
