# Generated by Django 3.1.1 on 2020-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cals', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
